### PR TITLE
Add an .ipynb with an example that calculates the transmission spectrum

### PR DESCRIPTION
**Pull request by mzamyatina**
The example uses the test data available at https://github.com/exoclim/aeolus_data.

### CODE REVIEW

**Comment by dennissergeev** [comment]
the `docs` workflow failed due to an unrelated issue, ignore it

**Comment by mzamyatina** [comment]
Hi @dachrist ! Could you review and test the functions mentioned in this Jupyter Notebook, please?
To view a rendered notebook go to the Files changed tab and once there click "..." to View file. If you would like to leave comments to specific lines in the notebook, click Load diff. Otherwise, please leave comments here.

**Review by dennissergeev — APPROVED** [review]
well done!

**Review by dachrist — APPROVED** [review]
Looks good.

**Comment by dennissergeev** [comment]
thanks @dachrist!

**Pull request merged**
